### ISSUE TITLE
Proper user profile image display for binder

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#30]
The user profile image shows a broken image when picture is not available in binder. The problem is same with that one fixed in traveler.
![screen shot 2018-09-11 at 9 13 28 am](https://user-images.githubusercontent.com/3741779/45365985-5bd85100-b5a3-11e8-80b4-65106c6e17fa.png)

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/35

**Comment by shengb** [comment]
This does not fix the "Reloads all tables". After clicking the "Reloads all tables", the image shows broken again.

**Comment by shengb** [comment]
fixed in #36

**Comment by shengb** [comment]
Reopen this issue because the same thing happens to the all public forms.
![screen shot 2018-09-19 at 3 36 51 pm](https://user-images.githubusercontent.com/3741779/45779877-df3c1700-bc21-11e8-8626-72b3cec258d2.png)

**Comment by shengb** [comment]
fix #50
